name: Validate

on:
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Yarn
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check types
        run: yarn run check-types

      - name: Check for lint issues
        run: yarn run check-lint
